### ISSUE TITLE
It does not support RTL

### ISSUE THREAD

**Issue by kareemel-sayed** [pengx17/logseq-dev-theme#107]
Thank you very much for this addition and for your great effort... But it does not support RTL please add it to us and you very much thank you

**Comment by PixelTux** [comment]
Hi @kareemel-sayed, I’m not an expert on RTL, but I wonder if other themes have this feature. I believe RTL support should be integrated into the app or offered as a specific plugin. Meanwhile, you might want to test this simple CSS tweak. Go to Settings -> General and edit custom.css an add:
```css
#main-container {
    direction: rtl;
    text-align: right;
}
```
Please let me know if this helps!
