### ISSUE TITLE
Bullet Threading Problems

### ISSUE THREAD

**Issue by zhengyu-yang** [pengx17/logseq-dev-theme#21]
1. The location of the bullet of a heading block will change when activated (from the center to the top of a block). 
![image](https://user-images.githubusercontent.com/25852061/146320478-4f178723-8ebd-41fe-bf13-d91cdd7f3692.png)
![image](https://user-images.githubusercontent.com/25852061/146320498-82550822-174f-44aa-af32-18866f7cee97.png)
2. I feel that the thread outside a coding block should not extend along with the coding block.
![image](https://user-images.githubusercontent.com/25852061/146320784-d9f105d7-7918-472b-a41d-679d09ce433a.png)

**Comment by pengx17** [comment]
The first issue is intended. This is because if I still draw the threading normally, it will go through the bullet like a kebab. So that as a workaround I moved the bullet to the top instead for headings. I do not have a proper way to solve this issue with CSS only 😅

For the second issue, I do not have an idea about how to fix it as well. However, this should be a small glitch we can ignore though, haha

**Comment by andyburris** [comment]
For Part 2, I think I have a fix (which is also a fix for another issue I noticed where checking a TODO box creates the same weird extension):

```css
.ls-block[haschild]:focus-within > div > .block-content-wrapper::before {
    /*border-color: var(--ls-block-bullet-active-color)*/
    border-color: transparent
}
```
Tested it a little and doesn't seem to break anything else, but not 100% sure on that so would be good to check on.
