### ISSUE TITLE
Highlight color

### ISSUE THREAD

**Issue by Bad3r** [pengx17/logseq-dev-theme#23]
Is it currently not possible to overwrite the highlight color? Its using logseq default theme color

![](https://user-images.githubusercontent.com/25513724/146644110-5840398d-400f-4b06-a6ec-a1e9cfcd8d52.png)

**Comment by ivanddm** [comment]
This is working for me to change the highlight color (adding it to my Logseq `custom.css` file):

```css
.block-highlight,
.dark-theme .content .selected {
  background-color: #313942 !important;
}
```

**Comment by pengx17** [comment]
I have updated the block selection color rule for dark mode.

**Comment by Bad3r** [comment]
@pengx17 For some reason this update is not taking effect when using   
\`\`\`  
@import url("https://cdn.jsdelivr.net/gh/pengx17/logseq-dev-theme@main/custom.css");  
\`\`\`

I see in the pr that you set   
\`\`\`CSS  
  --ls-block-highlight-color: var(--color-level-1);  
\`\`\`

This is available in `custom.css` but I can't find where you defined the value for `--color-level-1`? I can't find it anywhere

**Comment by pengx17** [comment]
@Bad3r `--color-level-1` is available in the context of Logseq. 
<img width="500" alt="截屏2021-12-22 上午1 13 02" src="https://user-images.githubusercontent.com/584378/146971140-a83fa1c1-8431-47fa-b95c-1a28f7365390.png">

The reason why the theme does not get updated in time might be caused by browser cache. You can try force refresh logseq and try again.

**Comment by Bad3r** [comment]
@pengx17 Thanks, it worked after I cleared the cache.
BTW, selecting a line in a code block still uses the default theme highlight color. To overwrite it, I added this to my custom.css file:
```CSS
.cm-s-solarized.cm-s-dark div.CodeMirror-selected { background: var(--color-level-3); }
```
