### ISSUE TITLE
Misaligned new page

### ISSUE THREAD

**Issue by idadzie** [pengx17/logseq-dev-theme#32]
The new page button position appears to be misaligned.

![2022-01-12_08-05](https://user-images.githubusercontent.com/4581114/149094678-9da00655-3895-456c-a24e-64dbef2d58bb.png)

Setting the position to relative in my **custom.css** seems to resolve the issue.

``` css
.left-sidebar-inner .new-page {
  position: relative;
  bottom: 0;
}
nav.px-2 {
  padding-bottom: .5rem;
}
```
![2022-01-12_08-54](https://user-images.githubusercontent.com/4581114/149095353-b251e0bf-1e28-4da9-9852-99d4bb648b4b.png)
