### ISSUE TITLE
Guidelines for changing some basic features

### ISSUE THREAD

**Issue by kerim** [pengx17/logseq-dev-theme#46]
Could you add a "how to" for those who would like to tweak some basic settings, such as the default colors for URL links and [[links]], as well as underlining tasks, font size, etc.?

**Comment by kerim** [comment]
Perhaps related, but I'd like to have a choice of color schemes for the dark mode. Right now everything is blue, but I'd like to have it be either green or orange... it might be nice to just be able to choose a basic color scheme without having to choose each color individually...

**Comment by pengx17** [comment]
Here is an example of how to override the default colors:

```css
.white-theme, .dark-theme {
  --ls-link-ref-text-color: red; /* Link colors */
  --ct-highlight-color: red; /* Highlight underline color */
}
```

A full list of the colors for reference:
https://github.com/pengx17/logseq-dev-theme/blob/main/custom.css#L1203-L1244

Note: due to layout issues (calculating threading offset etc), I do not have a "perfect" solution to changing font size.  But you may refer to https://github.com/pengx17/logseq-dev-theme/issues/33#issuecomment-1043050146.
