### ISSUE TITLE
请问如何修改代码块的字体

### ISSUE THREAD

**Issue by zwyyy456** [pengx17/logseq-dev-theme#60]
dev theme默认的字体似乎是fira code,个人不喜欢它的连字特性,然而在第一行`import url`那里将`Fira+Code`改成`Fira+Mono`之后,代码块的字体就变成了monaco,请问如何修改custom.css使得代码块字体为`Fira Mono`呢

**Comment by pengx17** [comment]
Hi, 可以试试在 custom.css 里增加这么一句
```css
:root {
  --ct-code-font-family: 'Fira Mono';
}
```

**Comment by zwyyy456** [comment]
这样尝试过,但是并没有效果...
最后是在`.CodeMirror`那里添加了font-family解决的
```css
.CodeMirror {
font-family: "Fira Mono" ...;
}
```
