### ISSUE TITLE
Change Font-Size Code Block

### ISSUE THREAD

**Issue by Figmenta1991** [pengx17/logseq-dev-theme#62]
I cannot find the css parameter to change the code block font size.
I can change the "inline code font size" with something such as  --ct-inline-code-font-size: 1.5em;
But I cannot change, let's say the "out code font size" or the font size of a block of code.

Can anyone help me? Thanks a lot!

**Comment by pengx17** [comment]
Please change font properties in `.CodeMirror` rules. E.g.:

```css
.CodeMirror {
   font-family: "Fira Mono";
   font-size: ...
}
```

**Comment by Marven11** [comment]
I have the same problem but css above doesn't work.
My problem was solved by using: 
```css
.CodeMirror pre.CodeMirror-line,
.CodeMirror-gutter,
.CodeMirror-gutters,
.CodeMirror-linenumber,
.CodeMirror-scroll,
.CodeMirror-sizer,
.CodeMirror {
  font-size: 22px;
  line-height: 1.5;
}
```
