### ISSUE TITLE
Bullet thread broken when block has vertical margin.

### ISSUE THREAD

**Issue by SainoNamkho** [pengx17/logseq-dev-theme#71]
![image](https://user-images.githubusercontent.com/23036788/176872168-e522eb07-9189-4b98-9fc1-aeb7dae44841.png)

```css
.ls-block {
    margin-bottom: 1rem;
}
```

**Comment by pengx17** [comment]
Sorry, the bullet threading does not work with `margin-bottom` on blocks. Please try using `padding-bottom` instead.

**Comment by SainoNamkho** [comment]
> Sorry, the bullet threading does not work with `margin-bottom` on blocks. Please try using `padding-bottom` instead.

`padding-bottom` does not collapse, so there will be too much at the end of nested blocks. 
I've find an ad-hoc solution
```css
.ls-block .ls-block:focus-within:not(.ls-block:first-of-type) > div > div.items-center::before {
    top: calc(-50% + var(--ls-block-bullet-threading-width) * 0.5 - 1px - 1rem);
}
```
The `-50% + var(--ls-block-bullet-threading-width) * 0.5 - 1px` is take from the source code, which actually needs to be at least
`(current .ls-block).padding-top + (previous .ls-block).border-bottom`
