### ISSUE TITLE
H2 could not be changed by custom.css

### ISSUE THREAD

**Issue by CodingXCat** [pengx17/logseq-dev-theme#78]
I'm trying to add color to headers like this
``` css
/* Header*/
h1, h2, h3, h4 {
  color: #9bc4fe;
  font-weight: bold;
}
```

but the color of H2 could not be changed:
![image](https://user-images.githubusercontent.com/1538579/192244415-b35a8d97-42e2-4bcc-85ab-189799c21cd7.png)

**Comment by asandikci** [comment]
You can use `!important` tag to override previous color

```css
/* Header*/
h1, h2, h3, h4 {
  color: #9bc4fe !important;
  font-weight: bold;
}
```

![image](https://user-images.githubusercontent.com/94538585/200244234-1e04a7ac-d15c-40f7-936d-86aca00ff2b8.png)
