### ISSUE TITLE
Use Mono Spaced Font During Editing

### ISSUE THREAD

**Issue by zhengyu-yang** [pengx17/logseq-dev-theme#8]
I think it would be really helpful that during editing, the font in the focused block will automatically switch to a mono spaced font. For example, when I am editing a marked down table, mono sized font will make alignment much easier. Currently, my hot fix is adding this to the custom css file:

```css
.editor-wrapper{
  font-family: var(--ct-code-font-family);
}
```
