### ISSUE TITLE
The variable --ct-inline-code-color is missing

### ISSUE THREAD

**Issue by reprintsev** [pengx17/logseq-dev-theme#82]
The `--ct-inline-code-color` variable is missing, so the text color in the block is white. It works if you add a variable to the block:

As a workaround, add a variable to the block (example for dark mode)
```css
:root {
  --ct-inline-code-font-size: 0.85em;
  --ct-inline-code-color: #839496;
  --ct-inline-code-font-style: inherit;
  --ct-inline-code-border-radius: 2px;
  --ct-inline-code-padding: 2px 5px;
}
```
