### ISSUE TITLE
Priority Marker Emoji White Space Collapsed

### ISSUE THREAD

**Issue by zhengyu-yang** [pengx17/logseq-dev-theme#9]
On MacOS, the white spaces of priority marker emojis collapse. Probably related to [this](https://stackoverflow.com/questions/42016125/emoji-rendered-in-chrome-have-different-widths-than-in-other-browsers).
![image](https://user-images.githubusercontent.com/25852061/134842270-1a35e53d-e074-49e0-b350-ed8292da2469.png)

Proposed solution: use both `::before` and `::after` to enforce margin on the emojis.
My `custom.css`:
```css
/* priority marker emoji white space collapse */
a[priority]::after {
  font-size: var(--ct-inline-code-font-size);
}

a[priority="A"]::before,
a.priority[href="#/page/A" i]:before {
  content: "🔴";
  visibility: visible;
}

a[priority="B"]::before,
a.priority[href="#/page/B" i]:before {
  content: "🟡";
  visibility: visible;
}

a[priority="C"]::before,
a.priority[href="#/page/C" i]:before {
  content: "🟢";
  visibility: visible;
}

a[priority="A"]::after,
a.priority[href="#/page/A" i]:after {
  content: "A";
  visibility: visible;
}

a[priority="B"]::after,
a.priority[href="#/page/B" i]:after {
  content: "B";
  visibility: visible;
}

a[priority="C"]::after,
a.priority[href="#/page/C" i]:after {
  content: "C";
  visibility: visible;
}

a[priority]::before,
a.priority:before {
  width: initial;
  margin-left: 0;
  margin-right: .5em;
}

a[priority]::after,
a.priority:after {
  border-radius: 50%;
  color: var(--ls-primary-text-color);
  display: inline-block;
  font-size: 16px;
  font-weight: 600;
  height: 1rem;
  line-height: 1rem;
  text-align: center;
  margin-right: .3em;
}
```

After fix:
![image](https://user-images.githubusercontent.com/25852061/134842692-dea8368c-50dc-4368-ab4a-3c05c9d4e0b6.png)
